### ISSUE TITLE
Lock GUI cleanup dialogs

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#10]
Lock GUI function doesn't clean up dialogs (for instance if called from settings, settings dialog is displayed over lock screen).

**Comment by zigapk** [comment]
Similar issue happens in setup. Pressing `ctrl+L` sets keyboard focus to lock screen and strange things follow.

**Comment by matejm** [comment]
Now locking with `Ctrl+L` is not possible if any window is overlaying main window nor in setup. Mabye cleanup should be added when app is auto-locked after timeout, but this will be covered in #2.

**Comment by matejm** [comment]
When locking, dialogs are still not closed.
When some dialogs are opened, app should not have to be locked (e.g. file dialog)

**Comment by matejm** [comment]
All dialogs are closed when app is locked.
