### ISSUE TITLE
Import from backup check

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#11]
When importing from backup, application should check if backup file is valid. It should also ask user for password. If backup file is invalid, or user doesn't remember his or her password, it should not restore from that backup file.

**Comment by matejm** [comment]
TODO
- check if file is valid json wallet object
- ask user for password (new dialog)
- if decrypt was successful, then copy file

**Comment by viddrobnic** [comment]
Checking should also be done in setup when restoring from backup.
