### ISSUE TITLE
Open item URL

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#12]
Most URLs are not opened when clicked.

**Comment by matejm** [comment]
Issue seems to be platfrom specific. Using gnome, everything works perfectly
Tested urls;
https://www.google.com
www.google.com
google.com
github.com
putka.upm.si
bokunopico.com

**Comment by matejm** [comment]
Now testing in Ubuntu:
https://www.google.com/ works as expected.
Any other url, which doesn't starts with `https://` or `http://` doesn't work. However, error is printed:

    gvfs-open: google.com: error opening location: Error when getting information for file '/home/jmatejm/Desktop/electronpass-desktop/build/google.com': No such file or directory

(Of course `/home/matejm/Desktop/electronpass-desktop/build` is folder from where I launched app)

It seems that [QDesktopServices.openUrl()](http://doc.qt.io/qt-4.8/qdesktopservices.html#openUrl) using [tolerant mode](http://doc.qt.io/qt-4.8/qurl.html#ParsingMode-enum) doesn't work as expected.
