### ISSUE TITLE
Test packages and possibly add Arch package

### ISSUE THREAD

**Issue by zigapk** [electronpass/electronpass-desktop#15]
All the paclages have to be tested prior to alpha release.

Arch package could be added.

**Comment by viddrobnic** [comment]
Packages and app image need to be tested on:
- [x] arch
- [x] debian
- [x] ubuntu
- [x] fedora [icon for installed rpm package not working]
- [x] elementary os [ui not working: ```QApplication: invalid style override passed, ignoring it.```]
- [x] linux mint  [ui not working: ```QApplication: invalid style override passed, ignoring it.```]
- [x] mac os

Desktop environments to test on:
- [x] gnome
- [x] kde [clear clipboard not working]
- [x] xfce
- [x] pantheon (elementary os) [ui not working: ```QApplication: invalid style override passed, ignoring it.```]
- [x] unity (ubuntu)
- [x] cinnamon (mint)  [ui not working: ```QApplication: invalid style override passed, ignoring it.```]
- [x] mate
- [x] lxde [clear clipboard not working]

**Comment by viddrobnic** [comment]
Summary of system test:
- auto clear clipboard not working on kde and lxde
- elementary os and linux mint report ``` QApplication: invalid style override passed, ignoring it.``` error which means that UI is not usable
