### ISSUE TITLE
Lock after timeout

### ISSUE THREAD

**Issue by zigapk** [electronpass/electronpass-desktop#2]
Lock wallet and gui after timeout, set in settings. Default could be 30s.

**Comment by viddrobnic** [comment]
No idea how to capture all the events to reset the lock timer, therefore removing it from 0.1 alpha milestone. We will get to it later.

**Comment by matejm** [comment]
Lock will be performed after application window is not focused for a selected delay. Partly, this was implemented in 93c5f63, but few other changes have to be implemented:

- [x] Lock should not be performed if `setupView` is opened
- [x] When certain dialogs are opened (`deleteConfirmationDialog`, `syncOnlinePasswordDialog` ...)
- [x] When other windows which overlay app are opened (file dialogs)
