### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#25]
Arch package needs to be build on travis. Since arch has high enough version of qt in official repositories, qt won't be packaged in the app itself, but will be listed as a dependency. Lib will also be a dependancy.

**Comment by zigapk** [comment]
Packages are available at [github.com/electronpass/arch-packages](https://github.com/electronpass/arch-packages). Travis implementation is yet to be done by @DzinVision

**Comment by zigapk** [comment]
Arch package repo now hosted at [electronpass/arch-packages](https://github.com/electronpass/arch-packages) as a release under current tag.
