### ISSUE TITLE
Mac os package

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#28]
Mac os application needs to be automatically build with all of the dependencies bundled in the .app.

**Comment by zigapk** [comment]
This could be done in [non-linux-packages](https://github.com/electronpass/non-linux-packages) as it was created for this.

@DzinVision please provide a script, capable of compiling and bundling binaries into .app on mac.

**Comment by viddrobnic** [comment]
The script `build.sh` works on mac since it is Unix/Linux environment. Instructions on deployment have also been added. Travis still needs to be configured to build mac package, but we all know that travis in general is a whole separate issue.

**Comment by matejm** [comment]
Travis build is yet to be made. See #42 for more information.
