### ISSUE TITLE
Roboto font is not included in deb package

### ISSUE THREAD

**Issue by matejm** [electronpass/electronpass-desktop#33]
Roboto font is probably not included in deb package or it is not correctly linked. For that reason, font in installed app is not same that font in built project.

Screenshoot:
![screenshot](https://cloud.githubusercontent.com/assets/10084453/26777918/6128771a-49df-11e7-80df-b99b284a8a3a.png)
On the left side is installed app and on the right side is app build on my system.

Same problem could possibly exist in other packages.
Possibly, this issue could be similar to issue #3.

**Comment by zigapk** [comment]
Try uncompressing the deb. It should tell us whether font it is not included at all or qml just can't find it.

**Comment by matejm** [comment]
I was unable to find font in uncompressed deb, but I was also unable to find `logo_transparent_dark_64.png` or `lock_background_dark.jpg`, which definetly **are** present in package.

I found that the same problem exists also in AppImage file.

**Comment by zigapk** [comment]
Curious. Maybe try installing electronpass-desktop with `make install` and check whether those files are installed. (Installing to a specific folder by adding `-DCMAKE_INSTALL_PREFIX` to cmake just like travis would also be a relevant test). Maybe we simply forgot to install them.

Unfortunately, I won't be able to test this today.

**Comment by zigapk** [comment]
Same issue can be seen when running electronpass-desktop from appimage on arch.

**Comment by matejm** [comment]
Currently `deb` package is not even build, to this issue does not exist anymore. Closing it.

When Travis build is fixed (#42) and this package is built, this issue can be reopened if necessary.
