### ISSUE TITLE
Failed to compute left/right minimum bearings

### ISSUE THREAD

**Issue by matejm** [electronpass/electronpass-desktop#37]
When app is opened, these 3 error messages are printed in terminal.

    Failed to compute left/right minimum bearings for ""
    Failed to compute left/right minimum bearings for ""
    Failed to compute left/right minimum bearings for ""

Everything looks as normal, but this should still be fixed. But firstly, I have to figure out which items are causing this error.

**Comment by matejm** [comment]
Dear Past Me: I am unable to reproduce this error now. If you don't provide additional details, I will close this issue.

**Comment by zigapk** [comment]
Closing for now, might be reopened when we reproduce this problem.
