### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [electronpass/electronpass-desktop#39]
Please provide the AppImage for download on GitHub Releases, thanks.
Possibly you might be interested in https://github.com/probonopd/uploadtool which simplifies this.

Reference:
AppImage/AppImageHub#15

**Comment by matejm** [comment]
AppImage file for initial release  [v0.1](https://github.com/electronpass/electronpass-desktop/releases/tag/v0.1)  was already included and we are planning to include it in every release. 

Continuous upload was also implemented, however I noticed that somehow [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) script fails to build AppImage (#40). I will try to fix it in a few days.

**Comment by matejm** [comment]
`AppImage`,  `deb`  and `rpm` binaries are uploaded after successful build.

Currently `AppImage` binary is not build due to some still unsolved errors. This is tracked in issue #40.
