### ISSUE TITLE
Setup syncing problems

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#41]
After setup the application atumatically tries to sync with one of the sync providers, even it the user hasn't set this up. It also doesn't store this preference in settings, so the user has to change the sync settings again after the app is closed.

This might have something to do with resetting the wallet. We should probably clear the settings after the wallet reset.

**Comment by zigapk** [comment]
Also, if setting up a new sync provider fails, app doesn't recognize it and saves the new sync settings although they are not valid.

**Comment by matejm** [comment]
Yes, probably we forgot to purge settings, when reseting the wallet. On fresh install these problems were not present.
