### ISSUE TITLE
File Dialog buggy

### ISSUE THREAD

**Issue by viddrobnic** [electronpass/electronpass-desktop#44]
Current file dialog is buggy. On windows opening the application takes a lot of time, beacuse of the file dialog being always loaded and only hidden. Also on mac, `macdeployqt` does noy produce a walid binary, because we are usong `QtQuick.Controls` version 1 and 2, and the deploy command links only one of those versions.

Possible fix is instead of using QML gile dialog, we should try using [`QFileFialog`](http://doc.qt.io/qt-5.9/qfiledialog.html) which shoul be only loaded when needed.

**Comment by zigapk** [comment]
I think we should switch to qtquickcontrols2 anyways. File dialog can be replaced, but qfiledialog might be problematic and is quite ugly. Some other alternatives should also be considered - an external library for example?
