### ISSUE TITLE
Setup existing user select sync service

### ISSUE THREAD

**Issue by matejm** [electronpass/electronpass-desktop#5]
Listview where existing user could select from where he wants to recover his wallet is not selectable.

After listview will be selectable, actual recovery from sync services sohuld be implemented.
(Probably just calling `setup`'s select synce service will work).

**Comment by zigapk** [comment]
[b5e8e5](https://github.com/electronpass/electronpass-desktop/commit/b5e8e5e54e3848e2cccd5f5247ceff6924f1b8d2) fixes GUI issue. Back end remains to be written @matejm

**Comment by matejm** [comment]
Requires some testing, but basic setup should work now.
