### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by ShalokShalom** [electronpass/electronpass-desktop#50]
Desktop Client written in QML.

Which Desktop Client?

What is this program all about?

**Comment by zigapk** [comment]
Hi @ShalokShalom. Electronpass is our spare time project aimed at creating a good open source alternative to proprietary password managers like Enpass, Dashlane, Lastpass etc.

At the moment it still remains a work in progress and is far from complete. However, the desktop client is already usable and can be tested. This repository contains the QML and C++ source code for the desktop client GUI.

More information can be found in our [manifesto](https://github.com/electronpass/manifesto). In case of any further questions simply reply to this issue.

Have a great day,
Ziga Patacko Koderman

**Comment by ShalokShalom** [comment]
Oh, wow. Nice

You might want to put that into the README. 

:wink:
